/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CashAccountForm: typeof import('./src/components/CashAccountForm.vue')['default']
    CashAccountList: typeof import('./src/components/CashAccountList.vue')['default']
    DistributionChart: typeof import('./src/components/DistributionChart.vue')['default']
    FetchTaskForm: typeof import('./src/components/FetchTaskForm.vue')['default']
    HoldingForm: typeof import('./src/components/HoldingForm.vue')['default']
    HoldingList: typeof import('./src/components/HoldingList.vue')['default']
    InvestmentForm: typeof import('./src/components/InvestmentForm.vue')['default']
    LiabilityForm: typeof import('./src/components/LiabilityForm.vue')['default']
    LiabilityList: typeof import('./src/components/LiabilityList.vue')['default']
    OverviewCard: typeof import('./src/components/OverviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    Watchlist: typeof import('./src/components/Watchlist.vue')['default']
    WatchlistForm: typeof import('./src/components/WatchlistForm.vue')['default']
  }
}
